name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, Test, and Analyze on SonarCloud
    runs-on: ubuntu-latest

    # (facultatif mais recommandé pour la déco PR)
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'

      - name: Build + Test + SonarCloud analysis
        env:
          # requis par Sonar Cloud
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          # utile pour la déco PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')


      - name: "cache of maven"
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonar-
